apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-volume
  namespace: tekton-builds
  labels:
    app: ace-tekton
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/systemsltd/tekton/tekton-docker/workspace"

