apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv-volume
  labels:
    app: tekton
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/systemsltd/tekton/tekton-learning/work"
