apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-serviceaccount
  namespace: tekton-builds

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: tekton-builds
  name: pod-reader
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: tekton-builds
roleRef: # points to my Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader # name of role
subjects: # points to my ServiceAccount
- kind: ServiceAccount
  name: my-serviceaccount # service account to bind to
  namespace: tekton-builds # ns of service account